services:
  - type: web
    name: spell-tts-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /health

    envVars:
      - key: MODELS_DIR
        value: /app/models

