services:
  - type: web
    name: spell-tts-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /health

    envVars:
      - key: MODELS_DIR
        value: /app/models
      - key: OMP_NUM_THREADS
        value: "1"
      - key: MKL_NUM_THREADS
        value: "1"

